name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clean
        run: mvn -ntp clean
        working-directory: ./github-calculator
      - name: Build
        run: mvn -ntp compile
        working-directory: ./github-calculator
      - name: Short tests
        run: mvn -ntp test -Dtest='CalculatorTest'
        working-directory: ./github-calculator
      - name: Long tests
        run: mvn -ntp test -Dtest='CalculatorTestThorough'
        working-directory: ./github-calculator

      - name: Package
        run: mvn -ntp package
        working-directory: ./github-calculator
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bakejared/github-actions-calculator

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}