name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clean
        run: mvn -ntp clean
        working-directory: ./github-calculator
      - name: Build
        run: mvn -ntp compile
        working-directory: ./github-calculator
      - name: Short tests
        run: mvn -ntp test -Dtest='CalculatorTest'
        working-directory: ./github-calculator
      - name: Long tests
        run: mvn -ntp test -Dtest='CalculatorTestThorough'
        working-directory: ./github-calculator