name: Docker Workflow
on:
  push:
    paths:
      - '**.java'
  workflow_dispatch:

jobs:
  build_Docker_image:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Clean
        run: mvn -ntp clean
        working-directory: C:/Users/18jab/CS204/GitActions/CI-CD-Actions/github-calculator/pom.xml
      - name: Build
        run: mvn -ntp compile
        working-directory: C:/Users/18jab/CS204/GitActions/CI-CD-Actions/github-calculator/pom.xml
      - name: Short tests
        run: mvn -ntp test -Dtest='CalculatorTest'
        working-directory: C:/Users/18jab/CS204/GitActions/CI-CD-Actions/github-calculator/pom.xml
      - name: Long tests
        run: mvn -ntp test -Dtest='CalculatorTestThorough'
        working-directory: C:/Users/18jab/CS204/GitActions/CI-CD-Actions/github-calculator/pom.xml